name: 'publish'
on:
    push:
        tags: [v\d+\.\d+\.\d+]

jobs:
    publish-tauri:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                include:
                    - target: x86_64-pc-windows-msvc
                      platform: windows-latest

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v3

            - name: Get version
              id: get_version
              uses: battila7/get-version-action@v2

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: Rust cache
              uses: swatinem/rust-cache@v2
              with:
                  workspaces: './src-tauri -> target'

            - name: install frontend dependencies
              run: npm install # change this to npm or pnpm depending on which one you use

            - name: Change Version
              env:
                  VERSION: '${{ steps.get_version.outputs.version-without-v }}'
              run: make change-version

            - name: Build Tauri App
              uses: tauri-apps/tauri-action@dev
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
              with:
                  tagName: Chatbox-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
                  releaseName: 'Chatbox v__VERSION__'
                  releaseBody: 'See the assets to download this version and install.'
                  releaseDraft: true
                  prerelease: false
                  args: --target ${{matrix.target}}
